import type { Story } from '@/types';

export const STORIES: Story[] = [
  {
    id: 'story_market',
    title: 'Shopping for Dates in the Souf Market',
    titleArabic: 'شرا التّمر في سوق السّوف',
    description: 'Practice haggling and market vocabulary as you shop for dates in El Oued.',
    coverImage: 'market',
    dialectId: 'algerian_eloued',
    isPremium: false,
    startNodeId: 'n1',
    nodes: [
      {
        id: 'n1',
        speaker: 'Vendor',
        textArabic: 'مرحبا بيك! واش حاب تشري اليوم؟',
        textTransliteration: 'marhba bik! wash hab teshri lyoum?',
        textEnglish: 'Welcome! What would you like to buy today?',
        vocabHighlights: ['eloued_market_5'],
        choices: [
          { id: 'c1', textArabic: 'نحب نشري تمر', textEnglish: 'I want to buy dates', nextNodeId: 'n2', isCorrect: true },
          { id: 'c2', textArabic: 'نحب نبيع تمر', textEnglish: 'I want to sell dates', nextNodeId: 'n2_wrong' },
        ],
      },
      {
        id: 'n2',
        speaker: 'Vendor',
        textArabic: 'باهي! عندي أحسن تمر في الوادي. بشحال تحب؟',
        textTransliteration: 'bahi! ʿandi ahsen temr fi el-wadi. beshhal tehb?',
        textEnglish: 'Great! I have the best dates in El Oued. How much do you want?',
        vocabHighlights: ['eloued_market_4'],
        choices: [
          { id: 'c3', textArabic: 'كيلو وحدة، من فضلك', textEnglish: 'One kilo, please', nextNodeId: 'n3', isCorrect: true },
        ],
      },
      {
        id: 'n2_wrong',
        speaker: 'Vendor',
        textArabic: 'هاها، ماكانش عندك تمر باش تبيع! جرّب مرّة أخرى.',
        textTransliteration: 'haha, makansh ʿandek temr bash tbiʿ! jarreb marra okhra.',
        textEnglish: "Haha, you don't have dates to sell! Try again.",
        choices: [{ id: 'c_retry', textArabic: 'نحب نشري تمر', textEnglish: 'I want to buy dates', nextNodeId: 'n2', isCorrect: true }],
      },
      {
        id: 'n3',
        speaker: 'Vendor',
        textArabic: 'هذا بخمسمية دينار.',
        textTransliteration: 'hada b-khamsmiya dinar.',
        textEnglish: 'That will be 500 dinars.',
        choices: [
          { id: 'c4', textArabic: 'غالي بزّاف، نقّصلي شوية', textEnglish: "That's expensive, give me a discount", nextNodeId: 'n4', isCorrect: true },
          { id: 'c5', textArabic: 'باهي، هاك الفلوس', textEnglish: "Okay, here's the money", nextNodeId: 'n_end_full_price' },
        ],
      },
      {
        id: 'n4',
        speaker: 'Vendor',
        textArabic: 'باهي، خاطرك زبون لطيف، نعطيك بأربعمية.',
        textTransliteration: 'bahi, khatrek zbun latif, naʿtik b-arbaʿmiya.',
        textEnglish: "Fine, since you're a nice customer, I'll give it to you for 400.",
        choices: [{ id: 'c6', textArabic: 'الله يعطيك الصحة!', textEnglish: 'Thank you (God give you health)!', nextNodeId: 'n_end_discount', isCorrect: true }],
      },
      {
        id: 'n_end_discount',
        speaker: 'Narrator',
        textArabic: 'اشتريت التّمر بسعر حسن، مبروك!',
        textTransliteration: "eshtreyt et-temr b-seʿr hasan, mabruk!",
        textEnglish: 'You bought the dates at a good price, congratulations!',
        isEnding: true,
      },
      {
        id: 'n_end_full_price',
        speaker: 'Narrator',
        textArabic: 'خلّصت الثّمن الكامل — في المرّة الجّاية حاول تفاوض!',
        textTransliteration: "khallast eth-thaman el-kamel — fi el-marra ej-jaya hawel tfawed!",
        textEnglish: 'You paid full price — next time try negotiating!',
        isEnding: true,
      },
    ],
  },
  {
    id: 'story_taxi',
    title: 'Taking a Taxi Across El Oued',
    titleArabic: 'الطّاكسي في الوادي',
    description: 'Order a taxi, give your destination, and chat with the driver.',
    coverImage: 'taxi',
    dialectId: 'algerian_eloued',
    isPremium: false,
    startNodeId: 't1',
    nodes: [
      {
        id: 't1',
        speaker: 'Driver',
        textArabic: 'أهلا، غادي لوين؟',
        textTransliteration: 'ahla, ghadi lwin?',
        textEnglish: 'Hi, where are you headed?',
        choices: [
          { id: 't_c1', textArabic: 'للسّوق من فضلك', textEnglish: 'To the market please', nextNodeId: 't2', isCorrect: true },
        ],
      },
      {
        id: 't2',
        speaker: 'Driver',
        textArabic: 'باهي، اركب. بشحال معاك وقت؟',
        textTransliteration: 'bahi, erkeb. beshhal maʿak weqt?',
        textEnglish: 'Okay, hop in. How much time do you have?',
        choices: [
          { id: 't_c2', textArabic: 'عندي وقت بزّاف', textEnglish: 'I have plenty of time', nextNodeId: 't3', isCorrect: true },
        ],
      },
      {
        id: 't3',
        speaker: 'Driver',
        textArabic: 'وصلنا! هذا بمية دينار.',
        textTransliteration: 'wselna! hada b-miya dinar.',
        textEnglish: "We've arrived! That's 100 dinars.",
        choices: [{ id: 't_c3', textArabic: 'شكرا، بالسّلامة', textEnglish: 'Thanks, goodbye', nextNodeId: 't_end', isCorrect: true }],
      },
      {
        id: 't_end',
        speaker: 'Narrator',
        textArabic: 'وصلت للسّوق بسلامة!',
        textTransliteration: 'wselt lessuq b-slama!',
        textEnglish: 'You arrived at the market safely!',
        isEnding: true,
      },
    ],
  },
];
