import type { VocabWord } from '@/types';

/**
 * El Oued (Souf) Arabic — Lisan's flagship dialect.
 *
 * Linguistic note: El Oued/Souf speech belongs to the Saharan/Bedouin family of
 * Algerian Arabic (unlike the urban "Darja" of Algiers/Oran). Characteristic
 * features encoded below:
 *   - /q/ (ق) is frequently realized as [g] in Bedouin-type roots (gal not qal).
 *   - Interdentals /θ/ /ð/ are often preserved or shifted to /t/ /d/ depending on word.
 *   - Heavy vocabulary tied to oasis/palm-grove agriculture (the Souf "ghout" sunken
 *     gardens), camel husbandry, and trans-Saharan trade routes.
 *   - Possession uses "ntaε / taεi" like broader Algerian Arabic.
 * Entries here reflect the general Saharan-Bedouin Algerian register attested for
 * the region; before shipping to production, have native Soufi speakers record
 * audio and sanity-check hyper-local slang, since micro-regional variation is real
 * even within El Oued town vs. surrounding Souf villages.
 */

export const ELOUED_VOCAB: VocabWord[] = [
  // ---------- Greetings ----------
  {
    id: 'eloued_greet_1',
    dialectId: 'algerian_eloued',
    arabic: 'السلام عليكم',
    transliteration: 'es-salamu εlaykum',
    ipa: '/es.sa.la.mu ʕa.laj.kum/',
    english: 'Peace be upon you (universal Arabic greeting)',
    category: 'greetings',
    difficulty: 1,
    exampleSentenceArabic: 'السلام عليكم يا خويا، كيفاش راك؟',
    exampleSentenceTranslit: 'es-salamu εlaykum ya khuya, kifash rak?',
    exampleSentenceEnglish: 'Peace be upon you, brother, how are you?',
    crossDialect: {
      msa: 'السلام عليكم (as-salāmu ʿalaykum)',
      moroccan: 'Salam ʿlik',
      egyptian: 'Salamu ʿalaykum',
      levantine: 'Salamlik / marhaba',
      tunisian: 'Salam ʿlikom',
      gulf: 'Salam ʿalaykum',
    },
  },
  {
    id: 'eloued_greet_2',
    dialectId: 'algerian_eloued',
    arabic: 'كيراك؟',
    transliteration: 'kirak? (m) / kiraki? (f)',
    ipa: '/ki.rak/',
    english: 'How are you?',
    category: 'greetings',
    difficulty: 1,
    exampleSentenceArabic: 'أهلا يا الغالي، كيراك اليوم؟',
    exampleSentenceTranslit: 'ahla ya l-ghali, kirak lyoum?',
    exampleSentenceEnglish: "Hey dear, how are you today?",
    crossDialect: {
      msa: 'كيف حالك؟ (kayfa ḥāluk)',
      moroccan: 'La bas ʿlik?',
      egyptian: 'Ezzayak?',
      levantine: 'Kifak?',
      tunisian: 'Chnowa ahwelek?',
      gulf: 'Shlonak?',
    },
    notes: 'Very Bedouin/Saharan form; Algiers uses "wesh rak" instead.',
  },
  {
    id: 'eloued_greet_3',
    dialectId: 'algerian_eloued',
    arabic: 'لاباس، الحمد لله',
    transliteration: 'labas, el-hamdulillah',
    ipa: '/la.bas al.ħam.du.lil.lah/',
    english: "I'm fine, thank God",
    category: 'greetings',
    difficulty: 1,
    crossDialect: {
      msa: 'أنا بخير، الحمد لله',
      moroccan: 'Labas, lhamdulillah',
      egyptian: 'Kwayyes, el-hamdulillah',
      levantine: 'Mnih, el-hamdulillah',
      tunisian: 'Labes, el-hamdulillah',
      gulf: 'Zain, el-hamdulillah',
    },
  },
  {
    id: 'eloued_greet_4',
    dialectId: 'algerian_eloued',
    arabic: 'صباح الخير',
    transliteration: 'sbah el-khir',
    ipa: '/sˤbaħ el.xiːr/',
    english: 'Good morning',
    category: 'greetings',
    difficulty: 1,
    crossDialect: { msa: 'صباح الخير', moroccan: 'Sbah lkhir', egyptian: 'Sabah el-kheir', levantine: 'Sabah el-kheir', tunisian: 'Sbah el-khir', gulf: 'Sabah el-kheir' },
  },
  {
    id: 'eloued_greet_5',
    dialectId: 'algerian_eloued',
    arabic: 'تصبح على خير',
    transliteration: 'tesbah εla khir',
    ipa: '/tesˤ.baħ ʕa.la xiːr/',
    english: 'Good night',
    category: 'greetings',
    difficulty: 1,
    crossDialect: { msa: 'تصبح على خير', moroccan: 'Tsbah ʿla khir', egyptian: 'Tisbah ʿala kheir', levantine: 'Tisbah ʿa kheir', tunisian: 'Tsbah ʿal khir', gulf: 'Tisbah ʿala kheir' },
  },
  {
    id: 'eloued_greet_6',
    dialectId: 'algerian_eloued',
    arabic: 'بالسلامة',
    transliteration: 'b-es-slama',
    ipa: '/bes.sla.ma/',
    english: 'Goodbye (go safely)',
    category: 'greetings',
    difficulty: 1,
    crossDialect: { msa: 'مع السلامة', moroccan: 'Bslama', egyptian: 'Maʿ el-salama', levantine: 'Maʿ el-salame', tunisian: 'Bislema', gulf: 'Maʿ el-salama' },
  },
  {
    id: 'eloued_greet_7',
    dialectId: 'algerian_eloued',
    arabic: 'مرحبا بيك',
    transliteration: 'marhba bik',
    ipa: '/marħ.ba biːk/',
    english: 'Welcome',
    category: 'greetings',
    difficulty: 1,
    crossDialect: { msa: 'أهلاً وسهلاً', moroccan: 'Merhba bik', egyptian: 'Ahlan wa sahlan', levantine: 'Ahlan feek', tunisian: 'Marhba bik', gulf: 'Hala wallah' },
  },

  // ---------- Daily speech ----------
  {
    id: 'eloued_daily_1',
    dialectId: 'algerian_eloued',
    arabic: 'واش راك دير؟',
    transliteration: 'wash rak dir?',
    ipa: '/waʃ raːk diːr/',
    english: 'What are you doing?',
    category: 'daily_life',
    difficulty: 2,
    crossDialect: { msa: 'ماذا تفعل؟', moroccan: 'Ash katdir?', egyptian: 'Bitiʿmel eh?', levantine: 'Shu ʿam taʿmel?', tunisian: 'Chnowa taʿmel?', gulf: 'Shu tsawwi?' },
  },
  {
    id: 'eloued_daily_2',
    dialectId: 'algerian_eloued',
    arabic: 'غادي لوين؟',
    transliteration: 'ghadi lwin?',
    ipa: '/ɣaː.di lwiːn/',
    english: 'Where are you going?',
    category: 'daily_life',
    difficulty: 2,
    crossDialect: { msa: 'إلى أين أنت ذاهب؟', moroccan: 'Fin ghadi?', egyptian: 'Rayeh fein?', levantine: 'Wein rayeh?', tunisian: 'Aweh baʿed?', gulf: 'Wein rayeh?' },
  },
  {
    id: 'eloued_daily_3',
    dialectId: 'algerian_eloued',
    arabic: 'باهي',
    transliteration: 'bahi',
    ipa: '/baː.hi/',
    english: 'Good / okay / nice',
    category: 'daily_life',
    difficulty: 1,
    notes: 'One of the most-used words in Souf speech — a general "good/fine/cool."',
    crossDialect: { msa: 'جيد', moroccan: 'Mezyan', egyptian: 'Kwayyes', levantine: 'Mnih', tunisian: 'Behi', gulf: 'Zain' },
  },
  {
    id: 'eloued_daily_4',
    dialectId: 'algerian_eloued',
    arabic: 'روح بالراحة',
    transliteration: 'ruh b-er-raha',
    ipa: '/ruːħ ber.raː.ħa/',
    english: 'Take it easy / go slow',
    category: 'expressions',
    difficulty: 2,
    crossDialect: { msa: 'اذهب بهدوء', moroccan: 'Sir bshweya', egyptian: 'Rooh bi-hodoo', levantine: 'Rooh ʿa mahlak', tunisian: 'Aamel beshwiya', gulf: 'Roh bi hoodoo' },
  },
  {
    id: 'eloued_daily_5',
    dialectId: 'algerian_eloued',
    arabic: 'بالضبط',
    transliteration: 'bezzabt',
    ipa: '/bez.zabtˤ/',
    english: 'Exactly',
    category: 'daily_life',
    difficulty: 2,
    crossDialect: { msa: 'بالضبط', moroccan: 'Bedabt', egyptian: 'Bezabt', levantine: 'Bezzabt', tunisian: 'Bel dhabt', gulf: 'Bedh-dhabt' },
  },
  {
    id: 'eloued_daily_6',
    dialectId: 'algerian_eloued',
    arabic: 'ماكانش مشكل',
    transliteration: 'makansh mushkil',
    ipa: '/ma.kaːnʃ muʃ.kil/',
    english: "No problem / there's no issue",
    category: 'expressions',
    difficulty: 2,
    crossDialect: { msa: 'لا توجد مشكلة', moroccan: 'Makayn mushkil', egyptian: 'Mafish mushkila', levantine: 'Mafi mishkle', tunisian: 'Ma famech mushkil', gulf: 'Ma fi mushkila' },
  },
  {
    id: 'eloued_daily_7',
    dialectId: 'algerian_eloued',
    arabic: 'شكون نتا؟',
    transliteration: 'shkun nta?',
    ipa: '/ʃkun nta/',
    english: 'Who are you?',
    category: 'daily_life',
    difficulty: 1,
    crossDialect: { msa: 'من أنت؟', moroccan: 'Shkun nta?', egyptian: 'Meen enta?', levantine: 'Meen inte?', tunisian: 'Shkoon inti?', gulf: 'Minik?' },
  },
  {
    id: 'eloued_daily_8',
    dialectId: 'algerian_eloued',
    arabic: 'قداش الساعة؟',
    transliteration: 'gddash es-saεa?',
    ipa: '/gd.daːʃ es.saː.ʕa/',
    english: 'What time is it?',
    category: 'time',
    difficulty: 2,
    notes: 'The "g" for classical ق (qaf) — a Bedouin/Saharan hallmark heard clearly in "gddash."',
    crossDialect: { msa: 'كم الساعة؟', moroccan: 'Sh7al f sae?', egyptian: 'El-saʿa kam?', levantine: 'Add-esh el-saʿa?', tunisian: 'Chad el-hin?', gulf: 'Kam el-saʿa?' },
  },

  // ---------- Family ----------
  {
    id: 'eloued_fam_1',
    dialectId: 'algerian_eloued',
    arabic: 'بابا',
    transliteration: 'baba',
    ipa: '/baː.ba/',
    english: 'Father / dad',
    category: 'family',
    difficulty: 1,
    crossDialect: { msa: 'أب', moroccan: 'Bba', egyptian: 'Baba', levantine: 'Baba', tunisian: 'Baba', gulf: 'Wālid / Baba' },
  },
  {
    id: 'eloued_fam_2',
    dialectId: 'algerian_eloued',
    arabic: 'يمّا',
    transliteration: 'yemma',
    ipa: '/jem.ma/',
    english: 'Mother / mom',
    category: 'family',
    difficulty: 1,
    crossDialect: { msa: 'أم', moroccan: 'Mmi / Yemma', egyptian: 'Mama', levantine: 'Emmi', tunisian: 'Yemma', gulf: 'Māma' },
  },
  {
    id: 'eloued_fam_3',
    dialectId: 'algerian_eloued',
    arabic: 'جدّي',
    transliteration: 'jeddi',
    ipa: '/dʒed.di/',
    english: 'Grandfather',
    category: 'family',
    difficulty: 1,
    crossDialect: { msa: 'جدّي', moroccan: 'Jeddi', egyptian: 'Geddo', levantine: 'Jiddo', tunisian: 'Jeddi', gulf: 'Jaddi' },
  },
  {
    id: 'eloued_fam_4',
    dialectId: 'algerian_eloued',
    arabic: 'جدّتي',
    transliteration: 'jeddti',
    ipa: '/dʒedː.ti/',
    english: 'Grandmother',
    category: 'family',
    difficulty: 1,
    crossDialect: { msa: 'جدّتي', moroccan: 'Jeddti', egyptian: 'Teta', levantine: 'Sitto', tunisian: 'Jeddti', gulf: 'Jadda' },
  },
  {
    id: 'eloued_fam_5',
    dialectId: 'algerian_eloued',
    arabic: 'خويا',
    transliteration: 'khuya',
    ipa: '/xu.ja/',
    english: 'My brother',
    category: 'family',
    difficulty: 1,
    crossDialect: { msa: 'أخي', moroccan: 'Khoya', egyptian: 'Akhoya', levantine: 'Khayye', tunisian: 'Khoya', gulf: 'Akhoy' },
  },
  {
    id: 'eloued_fam_6',
    dialectId: 'algerian_eloued',
    arabic: 'ختي',
    transliteration: 'khti',
    ipa: '/xti/',
    english: 'My sister',
    category: 'family',
    difficulty: 1,
    crossDialect: { msa: 'أختي', moroccan: 'Khti', egyptian: 'Okhti', levantine: 'Khayyte', tunisian: 'Okhti', gulf: 'Ekhti' },
  },
  {
    id: 'eloued_fam_7',
    dialectId: 'algerian_eloued',
    arabic: 'عمّي',
    transliteration: 'εammi',
    ipa: '/ʕam.mi/',
    english: "Uncle (father's brother) / also polite term for older man",
    category: 'family',
    difficulty: 1,
    crossDialect: { msa: 'عمّي', moroccan: 'ʿAmmi', egyptian: 'ʿAmmo', levantine: 'ʿAmmo', tunisian: 'ʿAmmi', gulf: 'ʿAmmi' },
  },
  {
    id: 'eloued_fam_8',
    dialectId: 'algerian_eloued',
    arabic: 'خالتي',
    transliteration: 'khalti',
    ipa: '/xal.ti/',
    english: "Aunt (mother's sister)",
    category: 'family',
    difficulty: 1,
    crossDialect: { msa: 'خالتي', moroccan: 'Khalti', egyptian: 'Khalti', levantine: 'Khalte', tunisian: 'Khalti', gulf: 'Khalti' },
  },
  {
    id: 'eloued_fam_9',
    dialectId: 'algerian_eloued',
    arabic: 'الدّار',
    transliteration: 'ed-dar',
    ipa: '/ed.daːr/',
    english: 'The house / the family household',
    category: 'family',
    difficulty: 2,
    notes: '"Ed-dar" also means "family" collectively, as in "kifash ed-dar?" (how is the family).',
    crossDialect: { msa: 'المنزل / العائلة', moroccan: 'Eddar', egyptian: 'El-beit', levantine: 'El-beit', tunisian: 'Eddar', gulf: 'El-bait' },
  },

  // ---------- Market ----------
  {
    id: 'eloued_market_1',
    dialectId: 'algerian_eloued',
    arabic: 'بشحال هذا؟',
    transliteration: 'beshhal hada?',
    ipa: '/beʃ.ħal ha.da/',
    english: 'How much is this?',
    category: 'market',
    difficulty: 2,
    exampleSentenceArabic: 'بشحال هذا التمر؟',
    exampleSentenceTranslit: 'beshhal hada et-temr?',
    exampleSentenceEnglish: 'How much are these dates?',
    crossDialect: { msa: 'بكم هذا؟', moroccan: 'Bshhal hada?', egyptian: 'Bikam da?', levantine: 'Addesh hayda?', tunisian: 'Bech-hal hedha?', gulf: 'Bikam hatha?' },
  },
  {
    id: 'eloued_market_2',
    dialectId: 'algerian_eloued',
    arabic: 'غالي بزّاف',
    transliteration: 'ghali bezzaf',
    ipa: '/ɣaː.li bez.zaːf/',
    english: 'Very expensive',
    category: 'market',
    difficulty: 2,
    crossDialect: { msa: 'غالٍ جدًا', moroccan: 'Ghali bzzaf', egyptian: 'Ghali awi', levantine: 'Ghale ktir', tunisian: 'Ghali barsha', gulf: 'Ghali wayed' },
  },
  {
    id: 'eloued_market_3',
    dialectId: 'algerian_eloued',
    arabic: 'نقّصلي شوية',
    transliteration: 'naqqasli shwiya',
    ipa: '/naq.qas.li ʃwi.ja/',
    english: 'Give me a small discount',
    category: 'market',
    difficulty: 3,
    notes: 'Haggling is expected in Souf markets — this phrase is essential.',
    crossDialect: { msa: 'خفّض لي قليلاً', moroccan: 'Naqqes li shwiya', egyptian: 'Nazzelli shwaya', levantine: 'Naqqesli shway', tunisian: 'Noqasli chwaya', gulf: 'Khaffidhli shway' },
  },
  {
    id: 'eloued_market_4',
    dialectId: 'algerian_eloued',
    arabic: 'التّمر',
    transliteration: 'et-temr',
    ipa: '/et.temr/',
    english: 'Dates (fruit)',
    category: 'market',
    difficulty: 1,
    notes: 'El Oued is famous across Algeria for its Deglet Nour dates grown in the ghout gardens.',
    crossDialect: { msa: 'التمر', moroccan: 'Ttmar', egyptian: 'Balah', levantine: 'Tamr', tunisian: 'Tmar', gulf: 'Tamr' },
  },
  {
    id: 'eloued_market_5',
    dialectId: 'algerian_eloued',
    arabic: 'السّوق',
    transliteration: 'es-suq',
    ipa: '/es.suːq/',
    english: 'The market',
    category: 'market',
    difficulty: 1,
    crossDialect: { msa: 'السوق', moroccan: 'Ssuq', egyptian: 'El-souq', levantine: 'El-souq', tunisian: 'Souk', gulf: 'El-souq' },
  },
  {
    id: 'eloued_market_6',
    dialectId: 'algerian_eloued',
    arabic: 'عطيني هاذوك',
    transliteration: 'εatini hadhuk',
    ipa: '/ʕtˤiː.ni haː.ðuːk/',
    english: 'Give me those',
    category: 'market',
    difficulty: 2,
    crossDialect: { msa: 'أعطني تلك', moroccan: 'ʿAtini hadok', egyptian: 'Idini dol', levantine: 'Aʿtini hadole', tunisian: 'Aʿtini hedhoukom', gulf: 'Aʿtini hadolak' },
  },

  // ---------- Religious phrases ----------
  {
    id: 'eloued_rel_1',
    dialectId: 'algerian_eloued',
    arabic: 'ان شاء الله',
    transliteration: 'in sha allah',
    ipa: '/in.ʃal.laːh/',
    english: 'God willing',
    category: 'religion',
    difficulty: 1,
    crossDialect: { msa: 'إن شاء الله', moroccan: 'Nshallah', egyptian: 'Inshallah', levantine: 'Inshallah', tunisian: 'Inshallah', gulf: 'Inshallah' },
  },
  {
    id: 'eloued_rel_2',
    dialectId: 'algerian_eloued',
    arabic: 'الحمد لله',
    transliteration: 'el-hamdulillah',
    ipa: '/al.ħam.du.lil.laːh/',
    english: 'Praise be to God',
    category: 'religion',
    difficulty: 1,
    crossDialect: { msa: 'الحمد لله', moroccan: 'Lhamdulillah', egyptian: 'El-hamdulillah', levantine: 'El-hamdillah', tunisian: 'El-hamdulillah', gulf: 'El-hamdulillah' },
  },
  {
    id: 'eloued_rel_3',
    dialectId: 'algerian_eloued',
    arabic: 'بارك الله فيك',
    transliteration: 'barakallahu fik',
    ipa: '/ba.ra.kal.laː.hu fiːk/',
    english: 'May God bless you',
    category: 'religion',
    difficulty: 1,
    crossDialect: { msa: 'بارك الله فيك', moroccan: 'Barakallahu fik', egyptian: 'Barakallahu fik', levantine: 'Allah ybarek fik', tunisian: 'Barakallahu fik', gulf: 'Allah yebarek feek' },
  },
  {
    id: 'eloued_rel_4',
    dialectId: 'algerian_eloued',
    arabic: 'الله يعطيك الصحة',
    transliteration: 'allah yaʿtik es-saha',
    ipa: '/al.laːh jaʕ.tiːk es.sˤaħ.ħa/',
    english: 'May God give you health (thank you)',
    category: 'religion',
    difficulty: 2,
    notes: 'Extremely common way to say a heartfelt "thank you" across Algeria.',
    crossDialect: { msa: 'شكرًا جزيلاً', moroccan: 'Allah yaʿtik saha', egyptian: 'Rabbena yekhalik', levantine: 'Allah ysalmak', tunisian: 'Allah yaʿtik saha', gulf: 'Allah yeʿafeek' },
  },
  {
    id: 'eloued_rel_5',
    dialectId: 'algerian_eloued',
    arabic: 'الله يرحمو',
    transliteration: 'allah yerhamu',
    ipa: '/al.laːh jer.ħa.mu/',
    english: 'May God have mercy on him (said of the deceased)',
    category: 'religion',
    difficulty: 2,
    crossDialect: { msa: 'رحمه الله', moroccan: 'Allah yerhmou', egyptian: 'Allah yerhamo', levantine: 'Allah yerhamo', tunisian: 'Allah yerahmou', gulf: 'Allah yerhama' },
  },

  // ---------- Ramadan ----------
  {
    id: 'eloued_ramadan_1',
    dialectId: 'algerian_eloued',
    arabic: 'رمضان مبارك',
    transliteration: 'ramadan mubarak',
    ipa: '/ra.ma.dˤaːn mu.baː.rak/',
    english: 'Blessed Ramadan',
    category: 'ramadan',
    difficulty: 1,
    crossDialect: { msa: 'رمضان مبارك', moroccan: 'Ramadan mubarak', egyptian: 'Ramadan kareem', levantine: 'Ramadan mubarak', tunisian: 'Ramadan mubarak', gulf: 'Ramadan kareem' },
  },
  {
    id: 'eloued_ramadan_2',
    dialectId: 'algerian_eloued',
    arabic: 'الفطور',
    transliteration: 'el-ftur',
    ipa: '/el.ftˤuːr/',
    english: 'Iftar meal (breaking the fast)',
    category: 'ramadan',
    difficulty: 1,
    crossDialect: { msa: 'الإفطار', moroccan: 'Lftour', egyptian: 'El-fetar', levantine: 'El-iftar', tunisian: 'Ftour', gulf: 'El-iftar' },
  },
  {
    id: 'eloued_ramadan_3',
    dialectId: 'algerian_eloued',
    arabic: 'الشّهرية',
    transliteration: 'esh-shhriya',
    ipa: '/eʃ.ʃah.ri.ja/',
    english: 'Traditional Ramadan soup (Souf-style harira variant)',
    category: 'ramadan',
    difficulty: 2,
    notes: 'Local name for the tomato-and-legume soup families break their fast with in the Souf region.',
    crossDialect: { msa: 'الحساء', moroccan: 'Harira', egyptian: 'Shorba', levantine: 'Shorba', tunisian: 'Jari', gulf: 'Shorba' },
  },
  {
    id: 'eloued_ramadan_4',
    dialectId: 'algerian_eloued',
    arabic: 'السّحور',
    transliteration: 'es-suhur',
    ipa: '/es.su.huːr/',
    english: 'Suhoor (pre-dawn meal)',
    category: 'ramadan',
    difficulty: 1,
    crossDialect: { msa: 'السحور', moroccan: 'Sshour', egyptian: 'El-sohour', levantine: 'El-sohour', tunisian: 'Sahour', gulf: 'El-sohour' },
  },
  {
    id: 'eloued_ramadan_5',
    dialectId: 'algerian_eloued',
    arabic: 'صحّيت',
    transliteration: 'sahhit',
    ipa: '/sˤaħ.ħiːt/',
    english: 'Bon appétit (said after a meal too)',
    category: 'ramadan',
    difficulty: 1,
    crossDialect: { msa: 'بالهناء والشفاء', moroccan: 'Bsaha', egyptian: 'Beall hana', levantine: 'Sahtein', tunisian: 'Saha', gulf: 'Bel hana wel shifa' },
  },

  // ---------- Football ----------
  {
    id: 'eloued_football_1',
    dialectId: 'algerian_eloued',
    arabic: 'الكورة',
    transliteration: 'el-kura',
    ipa: '/el.ku.ra/',
    english: 'Football / the ball',
    category: 'football',
    difficulty: 1,
    crossDialect: { msa: 'كرة القدم', moroccan: 'Lkora', egyptian: 'El-kora', levantine: 'Kret ijer', tunisian: 'Kora', gulf: 'Kurat el-qadam' },
  },
  {
    id: 'eloued_football_2',
    dialectId: 'algerian_eloued',
    arabic: 'دار قول!',
    transliteration: 'dar goal!',
    ipa: '/daːr goːl/',
    english: 'He scored a goal!',
    category: 'football',
    difficulty: 2,
    crossDialect: { msa: 'سجّل هدفًا', moroccan: 'Dar goal', egyptian: 'Sagal gol', levantine: 'Saggal gol', tunisian: 'Dar goal', gulf: 'Sajjal hadaf' },
  },
  {
    id: 'eloued_football_3',
    dialectId: 'algerian_eloued',
    arabic: 'المنتخب',
    transliteration: 'el-muntakhab',
    ipa: '/el.mun.ta.xab/',
    english: 'The national team',
    category: 'football',
    difficulty: 2,
    crossDialect: { msa: 'المنتخب الوطني', moroccan: 'L-muntakhab', egyptian: 'El-muntakhab', levantine: 'El-muntakhab', tunisian: 'El-muntakhab', gulf: 'El-muntakhab' },
  },
  {
    id: 'eloued_football_4',
    dialectId: 'algerian_eloued',
    arabic: 'شدّ الماتش',
    transliteration: 'shedd el-match',
    ipa: '/ʃedd el.matʃ/',
    english: 'The match got intense',
    category: 'football',
    difficulty: 3,
    crossDialect: { msa: 'اشتدّت المباراة', moroccan: 'Shedd lmatch', egyptian: 'El-match hemi', levantine: 'El-match sar shu', tunisian: 'Shedd el-match', gulf: 'El-match hami' },
  },

  // ---------- School ----------
  {
    id: 'eloued_school_1',
    dialectId: 'algerian_eloued',
    arabic: 'المدرسة',
    transliteration: 'el-madrasa',
    ipa: '/el.mad.ra.sa/',
    english: 'School',
    category: 'school',
    difficulty: 1,
    crossDialect: { msa: 'المدرسة', moroccan: 'Lmadrasa', egyptian: 'El-madrasa', levantine: 'El-madrase', tunisian: 'El-madrasa', gulf: 'El-madrasa' },
  },
  {
    id: 'eloued_school_2',
    dialectId: 'algerian_eloued',
    arabic: 'الأستاذ',
    transliteration: 'el-ustadh',
    ipa: '/el.us.taːð/',
    english: 'Teacher (male)',
    category: 'school',
    difficulty: 1,
    crossDialect: { msa: 'الأستاذ', moroccan: 'L-ustad', egyptian: 'El-madares', levantine: 'El-ustaz', tunisian: 'El-ustedh', gulf: 'El-mudarris' },
  },
  {
    id: 'eloued_school_3',
    dialectId: 'algerian_eloued',
    arabic: 'واجب',
    transliteration: 'wajeb',
    ipa: '/waː.dʒeb/',
    english: 'Homework',
    category: 'school',
    difficulty: 1,
    crossDialect: { msa: 'واجب منزلي', moroccan: 'Wajeb', egyptian: 'Wageb', levantine: 'Fardh', tunisian: 'Wajeb', gulf: 'Wajeb manzeli' },
  },
  {
    id: 'eloued_school_4',
    dialectId: 'algerian_eloued',
    arabic: 'نجحت',
    transliteration: 'njaht',
    ipa: '/n.dʒaħt/',
    english: 'I passed / succeeded',
    category: 'school',
    difficulty: 2,
    crossDialect: { msa: 'نجحتُ', moroccan: 'Njaht', egyptian: 'Nagaht', levantine: 'Najahit', tunisian: 'Najjahet', gulf: 'Najahit' },
  },

  // ---------- Business ----------
  {
    id: 'eloued_biz_1',
    dialectId: 'algerian_eloued',
    arabic: 'الخدمة',
    transliteration: 'el-khedma',
    ipa: '/el.xed.ma/',
    english: 'Work / job',
    category: 'business',
    difficulty: 1,
    crossDialect: { msa: 'العمل', moroccan: 'Lkhedma', egyptian: 'Shoghl', levantine: 'Shughul', tunisian: 'Khedma', gulf: 'Shughul' },
  },
  {
    id: 'eloued_biz_2',
    dialectId: 'algerian_eloued',
    arabic: 'نتفقو على السّعر',
    transliteration: 'netfaqu εla es-seʿr',
    ipa: '/net.faː.qu ʕa.la es.seʕr/',
    english: 'We agree on the price',
    category: 'business',
    difficulty: 3,
    crossDialect: { msa: 'نتفق على السعر', moroccan: 'Nettafqou ʿla taman', egyptian: 'Nettefeʾ ʿala el-seʿr', levantine: 'Mnettafeʾ ʿas-seʿer', tunisian: 'Naʿmlou ʿal-siʿr', gulf: 'Nettafeg ʿala el-seʿer' },
  },
  {
    id: 'eloued_biz_3',
    dialectId: 'algerian_eloued',
    arabic: 'الفاتورة',
    transliteration: 'el-fatura',
    ipa: '/el.fa.tuː.ra/',
    english: 'The invoice / bill',
    category: 'business',
    difficulty: 2,
    crossDialect: { msa: 'الفاتورة', moroccan: 'Lfatura', egyptian: 'El-fatura', levantine: 'El-fature', tunisian: 'El-fattoura', gulf: 'El-fatoora' },
  },

  // ---------- Marriage ----------
  {
    id: 'eloued_marriage_1',
    dialectId: 'algerian_eloued',
    arabic: 'العرس',
    transliteration: 'el-εers',
    ipa: '/el.ʕers/',
    english: 'The wedding',
    category: 'marriage',
    difficulty: 1,
    notes: 'Souf weddings traditionally run several days, with distinct henna-night songs.',
    crossDialect: { msa: 'حفل الزفاف', moroccan: 'Lʿers', egyptian: 'El-farah', levantine: 'El-ʿirs', tunisian: 'El-ʿirs', gulf: 'El-ʿirs' },
  },
  {
    id: 'eloued_marriage_2',
    dialectId: 'algerian_eloued',
    arabic: 'مبروك العقد',
    transliteration: 'mabruk el-εaqd',
    ipa: '/mab.ruːk el.ʕaqd/',
    english: 'Congratulations on the engagement/marriage contract',
    category: 'marriage',
    difficulty: 2,
    crossDialect: { msa: 'مبروك الخطوبة', moroccan: 'Mabrouk lʿaqd', egyptian: 'Mabrouk el-katb', levantine: 'Mabrouk el-katb ketab', tunisian: 'Mabrouk el-milek', gulf: 'Mabrook el-melcha' },
  },
  {
    id: 'eloued_marriage_3',
    dialectId: 'algerian_eloued',
    arabic: 'العروسة',
    transliteration: 'el-εarusa',
    ipa: '/el.ʕa.ruː.sa/',
    english: 'The bride',
    category: 'marriage',
    difficulty: 1,
    crossDialect: { msa: 'العروس', moroccan: 'Lʿarusa', egyptian: 'El-ʿarousa', levantine: 'El-ʿarous', tunisian: 'El-ʿarousa', gulf: 'El-ʿarous' },
  },

  // ---------- Slang & Expressions & Idioms ----------
  {
    id: 'eloued_slang_1',
    dialectId: 'algerian_eloued',
    arabic: 'صاحبي',
    transliteration: 'sahbi',
    ipa: '/sˤaħ.bi/',
    english: 'My friend / buddy',
    category: 'slang',
    difficulty: 1,
    crossDialect: { msa: 'صديقي', moroccan: 'Sahbi', egyptian: 'Sahby', levantine: 'Rfiʾi', tunisian: 'Sahbi', gulf: 'Sadeeqi' },
  },
  {
    id: 'eloued_slang_2',
    dialectId: 'algerian_eloued',
    arabic: 'هاذي حاجة أخرى',
    transliteration: 'hadhi haja okhra',
    ipa: '/haː.ði ħaː.dʒa uxr.a/',
    english: "That's a whole different thing (impressive)",
    category: 'expressions',
    difficulty: 3,
    crossDialect: { msa: 'هذا شيء آخر', moroccan: 'Hadi haja okhra', egyptian: 'Da haga tania', levantine: 'Hayda shi tani', tunisian: 'Hedhi haja okhra', gulf: 'Hathi shay thani' },
  },
  {
    id: 'eloued_slang_3',
    dialectId: 'algerian_eloued',
    arabic: 'راه ماشي هزار',
    transliteration: 'rah mashi hzar',
    ipa: '/raːh maː.ʃi hzaːr/',
    english: "It's not a joke / I'm serious",
    category: 'expressions',
    difficulty: 3,
    crossDialect: { msa: 'هذا ليس مزاحًا', moroccan: 'Machi hzar', egyptian: 'Mesh hazar', levantine: 'Mish hazar', tunisian: 'Mahouch hzar', gulf: 'Mub hazar' },
  },
  {
    id: 'eloued_slang_4',
    dialectId: 'algerian_eloued',
    arabic: 'اللي فات مات',
    transliteration: 'elli fat mat',
    ipa: '/el.li faːt maːt/',
    english: 'What\'s past is dead (let bygones be bygones)',
    category: 'idioms',
    difficulty: 3,
    notes: 'Common Maghrebi proverb, used often by elders in Souf to close an argument.',
    crossDialect: { msa: 'ما مضى فات', moroccan: 'Li fat mat', egyptian: 'Elli fat mat', levantine: 'Elli fat mat', tunisian: 'Elli fet met', gulf: 'Elli rah rah' },
  },
  {
    id: 'eloued_slang_5',
    dialectId: 'algerian_eloued',
    arabic: 'يدّيها في الرّمل',
    transliteration: "yeddiha fi er-remel",
    ipa: '/jed.diː.ha fir.re.mel/',
    english: "He's wasting his effort (lit. 'carrying it into the sand')",
    category: 'idioms',
    difficulty: 4,
    notes: "A Souf-specific idiom drawing on the region's desert landscape.",
    crossDialect: { msa: 'يضيّع جهده هباءً', moroccan: 'Kayghaber fi rrih', egyptian: 'Bydawer fel-mayya', levantine: 'ʿam yehret bel mayy', tunisian: 'Ykhaddem fel-khala', gulf: 'Yeḥreth bel-baḥar' },
  },
  {
    id: 'eloued_slang_6',
    dialectId: 'algerian_eloued',
    arabic: 'وعليكم يا الغالي',
    transliteration: 'ya l-ghali',
    ipa: '/ja el.ɣaː.li/',
    english: '"Dear/precious one" — a warm term of address',
    category: 'slang',
    difficulty: 2,
    crossDialect: { msa: 'يا عزيزي', moroccan: 'A lghali', egyptian: 'Ya ghali', levantine: 'Ya ghali', tunisian: 'Ya ghali', gulf: 'Ya ghali' },
  },
  {
    id: 'eloued_slang_7',
    dialectId: 'algerian_eloued',
    arabic: 'قهوة على الرّيق',
    transliteration: 'gahwa εla er-riq',
    ipa: '/gah.wa ʕa.la er.riːq/',
    english: 'Coffee on an empty stomach (a Souf morning ritual)',
    category: 'daily_life',
    difficulty: 3,
    crossDialect: { msa: 'قهوة الصباح', moroccan: 'Qhwa ʿla rriq', egyptian: 'Ahwa ʿala reeʾ', levantine: 'Ahwe ʿalrreeʾ', tunisian: 'Gahwa ʿal-riq', gulf: 'Gahwa ʿalreeg' },
  },
];

export const ELOUED_GRAMMAR_NOTES = [
  {
    id: 'eloued_gram_qaf',
    title: 'The Bedouin "g" for ق (qaf)',
    explanation:
      'In Souf speech, classical ق is often pronounced as a hard [g], especially in everyday verbs: "gal" (he said) instead of MSA "qāla", "gddash" (how much/how many) instead of "qaddāsh." This is shared with Gulf and Bedouin dialects but contrasts with Algiers city speech, which usually keeps [q] or shifts it to a glottal stop.',
    comparisons: {
      msa: 'قال (qāla)',
      algerian_algiers: 'qal (keeps the [q])',
      gulf: 'gal (same [g] shift)',
    },
  },
  {
    id: 'eloued_gram_negation',
    title: 'Negation with ma___sh',
    explanation:
      'Like most Maghrebi dialects, El Oued wraps the verb in "ma...sh": "makansh" (there isn\'t), "mafhemtsh" (I didn\'t understand). This circumfix negation is a defining Maghrebi feature absent from most eastern dialects.',
    comparisons: {
      egyptian: 'Also uses ma___sh (mafahemtish) — a shared Afroasiatic substrate feature.',
      levantine: 'Uses simple "mish/ma" without the trailing -sh in most cases.',
    },
  },
  {
    id: 'eloued_gram_possession',
    title: 'Possession with ntaε / taεi',
    explanation:
      '"This book is mine" becomes "had el-ktab taεi" or "ntaε-i." This analytic possessive marker is used across Algeria and Morocco (Moroccan uses "dyal") but not in Egyptian/Levantine, which use "bitaʿ / taba /shi."',
    comparisons: {
      moroccan: 'dyali (mine) — same structure, different word.',
      egyptian: 'bitaʿi (mine).',
    },
  },
];
